name: 'build and deploy for server'
on:
    push:
        branches: [ master ]
jobs:
    build:
        name: 'Build & Publish'
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v2
            -   name: "Set up QEMU"
                uses: docker/setup-qemu-action@v3
            -   name: "Set up Docker Buildx"
                uses: docker/setup-buildx-action@v3
            -   name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    registry: ${{ secrets.REGISTRY_URL }}
                    username: ${{ secrets.REGISTRY_USERNAME }}
                    password: ${{ secrets.REGISTRY_TOKEN }}

            -   name: "Build"
                uses: docker/build-push-action@v5
                with:
                    context: ./src/Service
                    file: ./src/Service/Pepegov.Identity.PL/Dockerfile
                    push: true
                    tags: |
                        ${{ secrets.REGISTRY_URL }}/pepegov/identity:latest
                    secrets: |
                        "ASPNETCORE_ENVIRONMENT=Release"
                        "APPSETTINGS_RABBITMQ_URL=${{ secrets.APPSETTINGS_RABBITMQ_URL }}"
                        "APPSETTINGS_RABBITMQ_HOST=${{ secrets.APPSETTINGS_RABBITMQ_HOST }}"
                        "APPSETTINGS_RABBITMQ_USER=${{ secrets.APPSETTINGS_RABBITMQ_USER }}"
                        "APPSETTINGS_RABBITMQ_PASSWORD=${{ secrets.APPSETTINGS_RABBITMQ_PASSWORD }}"
                        "APPSETTINGS_POSTGRES_URL=${{ secrets.APPSETTINGS_POSTGRES_URL }}"
                        "APPSETTINGS_POSTGRES_USER=${{ secrets.APPSETTINGS_POSTGRES_USER }}"
                        "APPSETTINGS_POSTGRES_PASSWORD=${{ secrets.APPSETTINGS_POSTGRES_PASSWORD }}"
                    build-args: |
                        build_mode=Release
    deploy:
        name: 'Deploy'
        runs-on: ubuntu-latest
        needs: build
        steps:
            -   name: "Run deploy on server"
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.SERVER_HOST }}
                    username: ${{ secrets.SERVER_USERNAME }}
                    key: ${{ secrets.SERVER_KEY }}
                    port: ${{ secrets.SERVER_PORT }}
                    passphrase : ${{ secrets.PASSPHRASE }}
                    script: |
                        cat ~/.docker_password.txt | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
                        cd ${{ secrets.DEPLOY_DIR }}
                        docker compose down
                        docker rmi -f ${{ secrets.REGISTRY_URL }}/pepegov/identity:latest || true 
                        docker compose pull
                        docker compose up -d